# Generated by Django 5.1 on 2024-08-30 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='الفئة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/', verbose_name='المرفق')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Cash', 'كاش'), ('Credit Card', 'كريدت كارد'), ('Bank Transfer', 'حوالة بنكية'), ('Western Union', 'ويسترن يونيون')], max_length=50, verbose_name='طريقة الدفع')),
                ('url', models.URLField(blank=True, null=True, verbose_name='الرابط')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب')),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستفيد')),
                ('iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='الايبان')),
                ('credit_card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='رقم بطاقة الائتمان')),
                ('card_holder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم حامل البطاقة')),
                ('cvv', models.CharField(blank=True, max_length=4, null=True, verbose_name='رمز CVV')),
            ],
            options={
                'verbose_name': 'طريقة الدفع',
                'verbose_name_plural': 'طرق الدفع',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='الهاتف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('subscriber_balance', models.CharField(blank=True, max_length=50, null=True, verbose_name='رصيد المشترك')),
            ],
            options={
                'verbose_name': 'مشترك',
                'verbose_name_plural': 'المشتركون',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الإجمالي')),
                ('payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الدفعة')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الرصيد')),
                ('status', models.CharField(choices=[('Paid', 'مسددة'), ('Partially Paid', 'مسددة جزئيا'), ('Unpaid', 'غير مسددة')], default='Unpaid', max_length=20, verbose_name='الحالة')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting_system.paymentmethod', verbose_name='طريقة الدفع')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounting_system.subscriber', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='الإجمالي')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting_system.invoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting_system.subscribe', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'عنصر الفاتورة',
                'verbose_name_plural': 'عناصر الفاتورة',
            },
        ),
    ]
