# Generated by Django 5.1 on 2024-08-30 06:43

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
            ],
        ),
        migrations.CreateModel(
            name='UserCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='اسم المستخدم')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('password', models.CharField(max_length=128, verbose_name='كلمة المرور')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.JSONField(verbose_name='الاعتمادات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ التقرير')),
                ('total_tasks', models.IntegerField(default=0, verbose_name='المهام الكليّة')),
                ('completed_tasks', models.IntegerField(default=0, verbose_name='المهام المكتملة')),
                ('overdue_tasks', models.IntegerField(default=0, verbose_name='المهام المتأخرة')),
                ('in_progress_tasks', models.IntegerField(default=0, verbose_name='المهام قيد التنفيذ')),
                ('points', models.IntegerField(default=0, verbose_name='النقاط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('priority', models.CharField(choices=[('High', 'عالية'), ('Medium', 'متوسطة'), ('Low', 'منخفضة')], default='Medium', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('Not Started', 'لم يبدأ'), ('In Progress', 'قيد التنفيذ'), ('Completed', 'منفذ')], default='Not Started', max_length=20, verbose_name='الحالة')),
                ('reminder_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التذكير')),
                ('comments', models.TextField(blank=True, verbose_name='التعليقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مخصص لـ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.category', verbose_name='التصنيف')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.goal', verbose_name='الهدف')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task', verbose_name='المهمة الأصل')),
                ('tags', models.ManyToManyField(blank=True, to='tasks.tag', verbose_name='الوسوم')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='الرسالة')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإرسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='المهمة')),
            ],
        ),
    ]
